"use client";

import React from "react";
import {
  Clock,
  Calendar,
  Binary,
  Hash,
  FileText,
  Image,
  Type,
  MessageCircle,
  Palette,
  CaseSensitive,
  Radio,
  FileCode,
  FileOutput,
  ListOrdered,
  FileJson,
  FileCode2,
  Shield,
  Key,
  Lock,
  Fingerprint,
  KeyRound,
  Wallet,
  Scan,
  FileCheck,
  MapPin,
  Globe,
  Phone,
  CreditCard,
  Link,
  Code,
  Link2,
  Smartphone,
  Share2,
  SmartphoneNfc,
  FileQuestion,
  Keyboard,
  BookOpen,
  Monitor,
  FileDigit,
  GitBranch,
  Network,
  CalendarClock,
  Braces,
  Calculator,
  Container,
  CodeXml,
  FileDown,
  Regex,
  BookMarked,
  Scale,
  Mail,
  FunctionSquare,
  Timer,
  Percent,
  Gauge,
  Wifi,
  QrCode,
  Camera,
  Thermometer,
  BarChart3,
  AlignLeft,
  Sparkles,
  TypeOutline,
  Minus,
  Highlighter,
  Replace,
  CalendarDays,
  Layout,
  Sprout,
  Wrench,
} from "lucide-react";

const ICON_SIZE = 16;

type IconComponent = React.ComponentType<{ size?: number; className?: string }>;

const slugToIcon: Record<string, IconComponent> = {
  "epoch-converter": Clock,
  "date-converter": Calendar,
  "base-converter": Binary,
  "roman-numeral-converter": Hash,
  "base64-file-converter": FileText,
  "base64-string-converter": FileCode,
  "hex-preview": Binary,
  "string-pipeline": Type,
  "base64-hex-message-decoder": MessageCircle,
  "color-converter": Palette,
  "case-converter": CaseSensitive,
  "text-to-nato-alphabet": Radio,
  "text-to-binary": Binary,
  "text-to-unicode": Type,
  "yaml-to-json-converter": FileJson,
  "yaml-to-toml": FileDown,
  "json-to-yaml-converter": FileJson,
  "json-to-toml": FileDown,
  "list-converter": ListOrdered,
  "toml-to-json": FileJson,
  "toml-to-yaml": FileDown,
  "xml-to-json": FileCode2,
  "json-to-xml": FileCode2,
  "markdown-to-html": FileCode2,
  "token-generator": Key,
  "hash-text": Hash,
  bcrypt: Lock,
  "uuid-generator": Fingerprint,
  "ulid-generator": Fingerprint,
  encryption: Lock,
  "bip39-generator": Wallet,
  "hmac-generator": Scan,
  "rsa-key-pair-generator": KeyRound,
  "password-strength-analyser": Shield,
  "pdf-signature-checker": FileCheck,
  "map-coordinate-converter": MapPin,
  "basic-auth-generator": Key,
  "phone-parser-and-formatter": Phone,
  "iban-validator-and-parser": CreditCard,
  "url-encoder": Link,
  "html-entities": Code,
  "url-parser": Link2,
  "device-information": Smartphone,
  "og-meta-generator": Share2,
  "otp-generator": SmartphoneNfc,
  "mime-types": FileQuestion,
  "jwt-parser": FileCode,
  "keycode-info": Keyboard,
  "slugify-string": Type,
  "html-wysiwyg-editor": Code,
  "user-agent-parser": Monitor,
  "http-status-codes": FileDigit,
  "json-diff": GitBranch,
  "safelink-decoder": Link,
  "query-string-builder": Link2,
  "git-memo": BookOpen,
  "random-port-generator": Network,
  "crontab-generator": CalendarClock,
  "json-prettify": Braces,
  "json-minify": Braces,
  "json-to-csv": FileOutput,
  "sql-prettify": FileCode,
  "chmod-calculator": Calculator,
  "docker-run-to-docker-compose-converter": Container,
  "xml-formatter": CodeXml,
  "yaml-prettify": FileDown,
  "regex-tester": Regex,
  "regex-memo": BookMarked,
  "semver-comparator": Scale,
  "email-normalizer": Mail,
  "math-evaluator": FunctionSquare,
  "eta-calculator": Timer,
  "percentage-calculator": Percent,
  "ipv4-subnet-calculator": Network,
  "ipv4-address-converter": Gauge,
  "ipv4-range-expander": Network,
  "mac-address-lookup": Monitor,
  "mac-address-generator": Network,
  "ipv6-ula-generator": Network,
  "qrcode-generator": QrCode,
  "wifi-qrcode-generator": Wifi,
  "svg-placeholder-generator": Image,
  "camera-recorder": Camera,
  chronometer: Timer,
  "temperature-converter": Thermometer,
  "benchmark-builder": BarChart3,
  "lorem-ipsum-generator": AlignLeft,
  "text-statistics": TypeOutline,
  "emoji-picker": Sparkles,
  "string-obfuscator": Type,
  "numeronym-generator": TypeOutline,
  "ascii-text-drawer": Type,
  "text-diff": Minus,
  "keyword-highlighter": Highlighter,
  "line-ending-converter": Replace,
  "schedule-workbench": CalendarDays,
  "css-style-gallery": Layout,
  "daily-grow": Sprout,
};

const defaultIcon: IconComponent = Wrench;

export function getToolIcon(slug: string): React.ReactNode {
  const Icon = slugToIcon[slug] ?? defaultIcon;
  return <Icon size={ICON_SIZE} className="shrink-0" />;
}
