export interface ToolConfig {
  slug: string;
  path: string;
  name: string;
  description: string;
  keywords: string[];
  category: string;
  redirectFrom?: string[];
  createdAt?: string;
}

export const toolsByCategory: { name: string; tools: ToolConfig[] }[] = [
  {
    name: "Converter",
    tools: [
      {
        slug: "epoch-converter",
        path: "/epoch-converter",
        name: "Timestamp converter",
        description: "Convert Unix timestamp (ms/s) to human-readable date (local & UTC).",
        keywords: ["epoch", "unix", "timestamp", "date", "utc", "converter"],
        category: "Converter",
      },
      {
        slug: "date-converter",
        path: "/date-converter",
        name: "Date/time converter",
        description: "Convert between common date/time formats.",
        keywords: [
          "date",
          "time",
          "converter",
          "iso",
          "utc",
          "timezone",
          "year",
          "month",
          "day",
          "minute",
          "seconde",
        ],
        category: "Converter",
      },
      {
        slug: "base-converter",
        path: "/base-converter",
        name: "Base converter",
        description: "Convert integers between bases (2-64).",
        keywords: [
          "integer",
          "number",
          "base",
          "conversion",
          "decimal",
          "hexadecimal",
          "binary",
          "octal",
          "base64",
        ],
        category: "Converter",
      },
      {
        slug: "roman-numeral-converter",
        path: "/roman-numeral-converter",
        name: "Roman numeral converter",
        description: "Convert Arabic numbers to Roman numerals and back.",
        keywords: ["roman", "arabic", "converter", "X", "I", "V", "L", "C", "D", "M"],
        category: "Converter",
      },
      {
        slug: "base64-file-converter",
        path: "/base64-file-converter",
        name: "Base64 file converter",
        description: "Convert between files and Base64 strings, with preview and download.",
        keywords: [
          "base64",
          "converter",
          "upload",
          "image",
          "file",
          "conversion",
          "web",
          "data",
          "format",
        ],
        category: "Converter",
      },
      {
        slug: "base64-string-converter",
        path: "/base64-string-converter",
        name: "Base64 string converter",
        description: "Convert strings to and from Base64, with URL safe options.",
        keywords: [
          "base64",
          "converter",
          "conversion",
          "web",
          "data",
          "format",
          "atob",
          "btoa",
        ],
        category: "Converter",
        redirectFrom: ["/file-to-base64", "/base64-converter"],
      },
      {
        slug: "hex-preview",
        path: "/hex-preview",
        name: "HEX preview",
        description: "",
        keywords: [
          "hex",
          "hexadecimal",
          "preview",
          "bytes",
          "dump",
          "viewer",
          "16进制",
        ],
        category: "Converter",
      },
      {
        slug: "string-pipeline",
        path: "/string-pipeline",
        name: "String pipeline",
        description: "Custom pipeline for string conversion.",
        keywords: ["string", "pipeline", "converter", "base64", "encode", "decode", "hex", "流程"],
        category: "Converter",
      },
      {
        slug: "base64-hex-message-decoder",
        path: "/base64-hex-message-decoder",
        name: "Base64 / hex message decoder",
        description: "Decode Base64 to hex bytes (with sequence numbers), edit, set timestamp to next minute, update CRC-CCITT (0x1D0F), re-encode to Base64.",
        keywords: ["base64", "hex", "decode", "message", "crc", "timestamp", "报文", "解码"],
        category: "Converter",
      },
      {
        slug: "color-converter",
        path: "/color-converter",
        name: "Color converter",
        description: "Convert between color formats (hex/rgb/hsl/etc).",
        keywords: ["color", "converter"],
        category: "Converter",
        redirectFrom: ["/color-picker-converter"],
      },
      {
        slug: "case-converter",
        path: "/case-converter",
        name: "Case converter",
        description: "Convert a string into various cases.",
        keywords: [
          "case",
          "converter",
          "camelCase",
          "capitalCase",
          "constantCase",
          "dotCase",
          "headerCase",
          "noCase",
          "paramCase",
          "pascalCase",
          "pathCase",
          "sentenceCase",
          "snakeCase",
        ],
        category: "Converter",
      },
      {
        slug: "text-to-nato-alphabet",
        path: "/text-to-nato-alphabet",
        name: "Text to NATO alphabet",
        description: "Convert text to NATO phonetic alphabet.",
        keywords: ["string", "nato", "alphabet", "phonetic", "oral", "transmission"],
        category: "Converter",
      },
      {
        slug: "text-to-binary",
        path: "/text-to-binary",
        name: "Text to binary",
        description: "Convert text to ASCII binary and back.",
        keywords: ["text", "to", "binary", "converter", "encode", "decode", "ascii"],
        category: "Converter",
        createdAt: "2023-10-15",
      },
      {
        slug: "text-to-unicode",
        path: "/text-to-unicode",
        name: "Text to Unicode",
        description: "Convert text to HTML Unicode entities and back.",
        keywords: ["text", "to", "unicode"],
        category: "Converter",
        createdAt: "2024-01-31",
      },
      {
        slug: "yaml-to-json-converter",
        path: "/yaml-to-json-converter",
        name: "YAML to JSON converter",
        description: "Convert YAML to JSON.",
        keywords: ["yaml", "to", "json"],
        category: "Converter",
        createdAt: "2023-04-10",
      },
      {
        slug: "yaml-to-toml",
        path: "/yaml-to-toml",
        name: "YAML to TOML",
        description: "Convert YAML to TOML.",
        keywords: ["yaml", "to", "toml", "convert", "transform"],
        category: "Converter",
        createdAt: "2023-06-23",
      },
      {
        slug: "json-to-yaml-converter",
        path: "/json-to-yaml-converter",
        name: "JSON to YAML converter",
        description: "Convert JSON to YAML.",
        keywords: ["yaml", "to", "json"],
        category: "Converter",
        createdAt: "2023-04-10",
      },
      {
        slug: "json-to-toml",
        path: "/json-to-toml",
        name: "JSON to TOML",
        description: "Convert JSON to TOML.",
        keywords: ["json", "parse", "toml", "convert", "transform"],
        category: "Converter",
        createdAt: "2023-06-23",
      },
      {
        slug: "list-converter",
        path: "/list-converter",
        name: "List converter",
        description: "Transform line-based lists with sorting, wrapping and formatting options.",
        keywords: ["list", "converter", "sort", "reverse", "prefix", "suffix", "lowercase", "truncate"],
        category: "Converter",
        createdAt: "2023-05-07",
      },
      {
        slug: "toml-to-json",
        path: "/toml-to-json",
        name: "TOML to JSON",
        description: "Convert TOML to JSON.",
        keywords: ["toml", "json", "convert", "online", "transform", "parser"],
        category: "Converter",
        createdAt: "2023-06-23",
      },
      {
        slug: "toml-to-yaml",
        path: "/toml-to-yaml",
        name: "TOML to YAML",
        description: "Convert TOML to YAML.",
        keywords: ["toml", "yaml", "convert", "online", "transform", "parse"],
        category: "Converter",
        createdAt: "2023-06-23",
      },
      {
        slug: "xml-to-json",
        path: "/xml-to-json",
        name: "XML to JSON",
        description: "Convert XML to JSON",
        keywords: ["xml", "json"],
        category: "Converter",
        createdAt: "2024-08-09",
      },
      {
        slug: "json-to-xml",
        path: "/json-to-xml",
        name: "JSON to XML",
        description: "Convert JSON to XML",
        keywords: ["json", "xml"],
        category: "Converter",
        createdAt: "2024-08-09",
      },
      {
        slug: "markdown-to-html",
        path: "/markdown-to-html",
        name: "Markdown to HTML",
        description: "Convert Markdown to Html and allow to print (as PDF)",
        keywords: ["markdown", "html", "converter", "pdf"],
        category: "Converter",
        createdAt: "2024-08-25",
      },
    ],
  },
  {
    name: "Crypto",
    tools: [
      {
        slug: "token-generator",
        path: "/token-generator",
        name: "Token generator",
        description: "Generate random string with the chars you want, uppercase or lowercase letters, numbers and/or symbols.",
        keywords: ["token", "generator", "random", "string", "uppercase", "lowercase", "numbers", "symbols"],
        category: "Crypto",
      },
      {
        slug: "hash-text",
        path: "/hash-text",
        name: "Hash text",
        description: "Hash a text string using the function you need: MD5, SHA1, SHA256, SHA224, SHA512, SHA384, SHA3 or RIPEMD160.",
        keywords: ["hash", "md5", "sha1", "sha256", "sha512", "ripemd160", "digest"],
        category: "Crypto",
      },
      {
        slug: "bcrypt",
        path: "/bcrypt",
        name: "bcrypt",
        description: "Hash and compare strings with bcrypt.",
        keywords: ["bcrypt", "hash", "password", "salt", "compare"],
        category: "Crypto",
      },
      {
        slug: "uuid-generator",
        path: "/uuid-generator",
        name: "UUIDs generator",
        description: "A Universally Unique Identifier (UUID) is a 128-bit number used to identify information in computer systems.",
        keywords: ["uuid", "generator", "v1", "v3", "v4", "v5", "nil"],
        category: "Crypto",
      },
      {
        slug: "ulid-generator",
        path: "/ulid-generator",
        name: "ULID generator",
        description: "Generate random Universally Unique Lexicographically Sortable Identifier (ULID).",
        keywords: ["ulid", "generator", "unique", "sortable"],
        category: "Crypto",
      },
      {
        slug: "encryption",
        path: "/encryption",
        name: "Encrypt / decrypt text",
        description: "Encrypt clear text and decrypt ciphertext using crypto algorithms like AES, TripleDES, Rabbit or RC4.",
        keywords: ["encryption", "decrypt", "encrypt", "aes", "tripledes", "rabbit", "rc4", "cipher"],
        category: "Crypto",
      },
      {
        slug: "bip39-generator",
        path: "/bip39-generator",
        name: "BIP39 generator",
        description: "Generate or convert BIP39 mnemonic phrase and entropy.",
        keywords: ["bip39", "mnemonic", "entropy", "seed", "wallet"],
        category: "Crypto",
      },
      {
        slug: "hmac-generator",
        path: "/hmac-generator",
        name: "HMAC generator",
        description: "Compute HMAC from a secret key and a message.",
        keywords: ["hmac", "hash", "mac", "signature", "sha256", "md5"],
        category: "Crypto",
      },
      {
        slug: "rsa-key-pair-generator",
        path: "/rsa-key-pair-generator",
        name: "RSA key pair generator",
        description: "Generate a new random RSA private and public PEM certificate key pair.",
        keywords: ["rsa", "key", "pair", "pem", "private", "public", "certificate"],
        category: "Crypto",
      },
      {
        slug: "password-strength-analyser",
        path: "/password-strength-analyser",
        name: "Password strength analyser",
        description: "Discover the strength of your password with this client-side-only password strength analyser and crack time estimation tool.",
        keywords: ["password", "strength", "crack", "entropy", "brute force"],
        category: "Crypto",
      },
      {
        slug: "pdf-signature-checker",
        path: "/pdf-signature-checker",
        name: "PDF signature checker",
        description: "Verify the signatures of a PDF file. A signed PDF file contains one or more signatures that may be used to determine whether the contents of the file have been altered since the file was signed.",
        keywords: ["pdf", "signature", "verify", "certificate", "digital signature"],
        category: "Crypto",
      },
    ],
  },
  {
    name: "Visualization",
    tools: [
      {
        slug: "map-coordinate-converter",
        path: "/map-coordinate-converter",
        name: "Map coordinate converter",
        description: "Convert between WGS84 (GPS), GCJ02 (Amap/Google China), and BD09 (Baidu) coordinate systems.",
        keywords: ["map", "coordinate", "WGS84", "GCJ02", "BD09", "GPS", "latitude", "longitude"],
        category: "Visualization",
      },
    ],
  },
  {
    name: "Web",
    tools: [
      {
        slug: "basic-auth-generator",
        path: "/basic-auth-generator",
        name: "Basic auth header generator",
        description:
          "Generate HTTP Basic Authorization headers from a username and password.",
        keywords: [
          "basic",
          "auth",
          "generator",
          "username",
          "password",
          "base64",
          "authentication",
          "header",
          "authorization",
        ],
        category: "Web",
      },
      {
        slug: "phone-parser-and-formatter",
        path: "/phone-parser-and-formatter",
        name: "Phone parser and formatter",
        description:
          "Parse, validate and format phone numbers. Get information about the phone number, like the country code, type, etc.",
        keywords: [
          "phone",
          "parser",
          "formatter",
          "validate",
          "format",
          "number",
          "telephone",
          "mobile",
          "cell",
          "international",
          "national",
        ],
        category: "Web",
        createdAt: "2023-05-01",
      },
      {
        slug: "iban-validator-and-parser",
        path: "/iban-validator-and-parser",
        name: "IBAN validator and parser",
        description:
          "Validate and parse IBAN numbers. Check if an IBAN is valid and get the country, BBAN, if it is a QR-IBAN and the IBAN friendly format.",
        keywords: ["iban", "validator", "and", "parser", "bic", "bank"],
        category: "Web",
        createdAt: "2023-08-26",
      },
      {
        slug: "url-encoder",
        path: "/url-encoder",
        name: "URL encoder",
        description: "Encode or decode a string for use in a URL.",
        keywords: ["url", "encoder", "decode", "encode", "percent"],
        category: "Web",
      },
      {
        slug: "html-entities",
        path: "/html-entities",
        name: "HTML entities",
        description: "Escape or unescape HTML entities.",
        keywords: ["html", "entities", "escape", "unescape"],
        category: "Web",
      },
      {
        slug: "url-parser",
        path: "/url-parser",
        name: "URL parser",
        description: "Parse a URL and display its components (protocol, hostname, path, params, etc.).",
        keywords: ["url", "parser", "parse", "query", "hostname"],
        category: "Web",
      },
      {
        slug: "device-information",
        path: "/device-information",
        name: "Device information",
        description: "Display screen and device information (resolution, orientation, user agent, etc.).",
        keywords: ["device", "screen", "browser", "user agent", "resolution"],
        category: "Web",
      },
      {
        slug: "og-meta-generator",
        path: "/og-meta-generator",
        name: "OG / Meta tag generator",
        description: "Generate Open Graph and Twitter meta tags for social sharing.",
        keywords: ["og", "meta", "open graph", "twitter", "social", "share"],
        category: "Web",
      },
      {
        slug: "otp-generator",
        path: "/otp-generator",
        name: "OTP generator & validator",
        description: "Generate TOTP codes and Key URI for authenticator apps.",
        keywords: ["otp", "totp", "2fa", "authenticator", "qr", "secret"],
        category: "Web",
      },
      {
        slug: "mime-types",
        path: "/mime-types",
        name: "MIME types",
        description: "Look up file extensions for MIME types and vice versa.",
        keywords: ["mime", "content-type", "extension", "file type"],
        category: "Web",
      },
      {
        slug: "jwt-parser",
        path: "/jwt-parser",
        name: "JWT parser",
        description: "Decode and inspect JWT (JSON Web Token) header and payload.",
        keywords: ["jwt", "token", "decode", "json web token"],
        category: "Web",
      },
      {
        slug: "keycode-info",
        path: "/keycode-info",
        name: "Keycode info",
        description: "Show key, keycode, code and modifiers for any key press.",
        keywords: ["keycode", "keyboard", "key", "event"],
        category: "Web",
      },
      {
        slug: "slugify-string",
        path: "/slugify-string",
        name: "Slugify string",
        description: "Convert a string into a URL-friendly slug.",
        keywords: ["slug", "slugify", "url", "string"],
        category: "Web",
      },
      {
        slug: "html-wysiwyg-editor",
        path: "/html-wysiwyg-editor",
        name: "HTML WYSIWYG editor",
        description: "Edit HTML in a simple WYSIWYG editor and see the output.",
        keywords: ["html", "wysiwyg", "editor", "rich text"],
        category: "Web",
      },
      {
        slug: "user-agent-parser",
        path: "/user-agent-parser",
        name: "User-Agent parser",
        description: "Parse a User-Agent string to see browser, OS, device and CPU.",
        keywords: ["user agent", "parser", "browser", "device"],
        category: "Web",
      },
      {
        slug: "http-status-codes",
        path: "/http-status-codes",
        name: "HTTP status codes",
        description: "Reference and search HTTP status codes (1xx–5xx).",
        keywords: ["http", "status", "code", "404", "500"],
        category: "Web",
      },
      {
        slug: "json-diff",
        path: "/json-diff",
        name: "JSON diff",
        description: "Compare two JSON objects and see the differences.",
        keywords: ["json", "diff", "compare", "difference"],
        category: "Web",
      },
      {
        slug: "safelink-decoder",
        path: "/safelink-decoder",
        name: "Safelink decoder",
        description: "Decode Outlook SafeLinks URLs to get the real destination URL.",
        keywords: ["safelink", "outlook", "decode", "url"],
        category: "Web",
      },
      {
        slug: "query-string-builder",
        path: "/query-string-builder",
        name: "Query string builder",
        description: "Build or parse URL query strings from key-value pairs.",
        keywords: ["query", "string", "url", "params", "search", "builder", "parse"],
        category: "Web",
      },
    ],
  },
  {
    name: "Development",
    tools: [
      {
        slug: "git-memo",
        path: "/git-memo",
        name: "Git memo",
        description: "Quick reference for common Git commands.",
        keywords: ["git", "memo", "cheatsheet", "commands"],
        category: "Development",
      },
      {
        slug: "random-port-generator",
        path: "/random-port-generator",
        name: "Random port generator",
        description: "Generate a random port number between 1024 and 65535.",
        keywords: ["port", "random", "generator", "network"],
        category: "Development",
      },
      {
        slug: "crontab-generator",
        path: "/crontab-generator",
        name: "Crontab generator",
        description: "Parse and describe cron expressions in human-readable form.",
        keywords: ["cron", "crontab", "schedule", "cronstrue"],
        category: "Development",
      },
      {
        slug: "json-prettify",
        path: "/json-prettify",
        name: "JSON prettify",
        description: "Format and prettify JSON with optional key sorting and indent size.",
        keywords: ["json", "prettify", "format", "beautify"],
        category: "Development",
      },
      {
        slug: "json-minify",
        path: "/json-minify",
        name: "JSON minify",
        description: "Minify JSON by removing whitespace.",
        keywords: ["json", "minify", "compress"],
        category: "Development",
      },
      {
        slug: "json-to-csv",
        path: "/json-to-csv",
        name: "JSON to CSV",
        description: "Convert a JSON array of objects to CSV.",
        keywords: ["json", "csv", "convert", "export"],
        category: "Development",
      },
      {
        slug: "sql-prettify",
        path: "/sql-prettify",
        name: "SQL prettify",
        description: "Format SQL with configurable dialect and keyword case.",
        keywords: ["sql", "prettify", "format", "formatter"],
        category: "Development",
      },
      {
        slug: "chmod-calculator",
        path: "/chmod-calculator",
        name: "Chmod calculator",
        description: "Calculate chmod octal and symbolic from read/write/execute checkboxes.",
        keywords: ["chmod", "permissions", "octal", "unix"],
        category: "Development",
      },
      {
        slug: "docker-run-to-docker-compose-converter",
        path: "/docker-run-to-docker-compose-converter",
        name: "Docker run to Compose converter",
        description: "Convert docker run command to docker-compose.yml.",
        keywords: ["docker", "compose", "converter", "composerize"],
        category: "Development",
      },
      {
        slug: "xml-formatter",
        path: "/xml-formatter",
        name: "XML formatter",
        description: "Format and indent XML.",
        keywords: ["xml", "format", "prettify", "indent"],
        category: "Development",
      },
      {
        slug: "yaml-prettify",
        path: "/yaml-prettify",
        name: "YAML prettify",
        description: "Format and prettify YAML with optional key sorting.",
        keywords: ["yaml", "prettify", "format", "beautify"],
        category: "Development",
      },
      {
        slug: "regex-tester",
        path: "/regex-tester",
        name: "Regex tester",
        description: "Test regular expressions with flags and see matches, captures and sample text.",
        keywords: ["regex", "tester", "regular expression", "match"],
        category: "Development",
      },
      {
        slug: "regex-memo",
        path: "/regex-memo",
        name: "Regex memo",
        description: "Regular expression cheatsheet and reference.",
        keywords: ["regex", "memo", "cheatsheet", "reference"],
        category: "Development",
      },
      {
        slug: "semver-comparator",
        path: "/semver-comparator",
        name: "SemVer comparator",
        description: "Compare two semantic version numbers (e.g. 1.2.3 vs 1.2.4).",
        keywords: ["semver", "version", "compare", "semantic versioning"],
        category: "Development",
      },
    ],
  },
  {
    name: "Data",
    tools: [
      {
        slug: "email-normalizer",
        path: "/email-normalizer",
        name: "Email normalizer",
        description:
          "Normalize email addresses to a standard format for easier comparison.",
        keywords: ["email", "normalizer"],
        category: "Data",
        createdAt: "2024-08-15",
      },
    ],
  },
  {
    name: "Math",
    tools: [
      {
        slug: "math-evaluator",
        path: "/math-evaluator",
        name: "Math evaluator",
        description: "Evaluate mathematical expressions (e.g. 2*sqrt(6)).",
        keywords: [
          "math",
          "evaluator",
          "calculator",
          "expression",
          "sqrt",
          "sin",
          "cos",
          "tan",
        ],
        category: "Math",
      },
      {
        slug: "eta-calculator",
        path: "/eta-calculator",
        name: "ETA calculator",
        description: "Estimate time of completion from rate and amount.",
        keywords: ["eta", "calculator", "estimated", "time", "arrival", "average"],
        category: "Math",
      },
      {
        slug: "percentage-calculator",
        path: "/percentage-calculator",
        name: "Percentage calculator",
        description: "Calculate percentages: X% of Y, X is what % of Y, increase/decrease.",
        keywords: ["percentage", "calculator", "calculate", "value", "number", "%"],
        category: "Math",
        createdAt: "2023-06-18",
      },
    ],
  },
  {
    name: "Network",
    tools: [
      {
        slug: "ipv4-subnet-calculator",
        path: "/ipv4-subnet-calculator",
        name: "IPv4 subnet calculator",
        description:
          "Parse your IPv4 CIDR blocks and get all the info you need about your subnet.",
        keywords: [
          "ipv4",
          "subnet",
          "calculator",
          "mask",
          "network",
          "cidr",
          "netmask",
          "bitmask",
          "broadcast",
          "address",
        ],
        category: "Network",
      },
      {
        slug: "ipv4-address-converter",
        path: "/ipv4-address-converter",
        name: "IPv4 address converter",
        description:
          "Convert an IP address into decimal, binary, hexadecimal, or even an IPv6 representation of it.",
        keywords: [
          "ipv4",
          "address",
          "converter",
          "decimal",
          "hexadecimal",
          "binary",
          "ipv6",
        ],
        category: "Network",
        createdAt: "2023-04-08",
      },
      {
        slug: "ipv4-range-expander",
        path: "/ipv4-range-expander",
        name: "IPv4 range expander",
        description:
          "Given a start and an end IPv4 address, this tool calculates a valid IPv4 subnet along with its CIDR notation.",
        keywords: ["ipv4", "range", "expander", "subnet", "creator", "cidr"],
        category: "Network",
        createdAt: "2023-04-19",
      },
      {
        slug: "mac-address-lookup",
        path: "/mac-address-lookup",
        name: "MAC address lookup",
        description:
          "Find the vendor / manufacturer information for a MAC address using the OUI database.",
        keywords: ["mac", "address", "lookup", "vendor", "parser", "manufacturer"],
        category: "Network",
        createdAt: "2023-04-06",
      },
      {
        slug: "mac-address-generator",
        path: "/mac-address-generator",
        name: "MAC address generator",
        description:
          "Generate random MAC addresses with an optional prefix, quantity, separator and case.",
        keywords: ["mac", "address", "generator", "random", "prefix"],
        category: "Network",
        createdAt: "2023-11-31",
      },
      {
        slug: "ipv6-ula-generator",
        path: "/ipv6-ula-generator",
        name: "IPv6 ULA generator",
        description:
          "Generate your own local, non-routable IP addresses for your network according to RFC4193.",
        keywords: ["ipv6", "ula", "generator", "rfc4193", "network", "private"],
        category: "Network",
        createdAt: "2023-04-09",
      },
    ],
  },
  {
    name: "Images and videos",
    tools: [
      {
        slug: "qrcode-generator",
        path: "/qrcode-generator",
        name: "QR Code generator",
        description:
          "Generate and download a QR code for a URL (or just plain text), and customize the background and foreground colors.",
        keywords: [
          "qr",
          "code",
          "generator",
          "square",
          "color",
          "link",
          "low",
          "medium",
          "quartile",
          "high",
          "transparent",
        ],
        category: "Images and videos",
      },
      {
        slug: "wifi-qrcode-generator",
        path: "/wifi-qrcode-generator",
        name: "WiFi QR Code generator",
        description:
          "Generate and download QR codes for quick connections to WiFi networks.",
        keywords: [
          "qr",
          "code",
          "generator",
          "square",
          "color",
          "link",
          "low",
          "medium",
          "quartile",
          "high",
          "transparent",
          "wifi",
        ],
        category: "Images and videos",
        createdAt: "2023-09-06",
      },
      {
        slug: "svg-placeholder-generator",
        path: "/svg-placeholder-generator",
        name: "SVG placeholder generator",
        description:
          "Generate SVG placeholder images with custom size, colors and text.",
        keywords: ["svg", "placeholder", "generator", "image", "size", "mockup"],
        category: "Images and videos",
      },
      {
        slug: "camera-recorder",
        path: "/camera-recorder",
        name: "Camera recorder",
        description:
          "Record videos and take screenshots from your camera directly in the browser.",
        keywords: ["camera", "recoder"],
        category: "Images and videos",
        createdAt: "2023-05-15",
      },
    ],
  },
  {
    name: "Measurement",
    tools: [
      {
        slug: "chronometer",
        path: "/chronometer",
        name: "Chronometer",
        description:
          "Monitor the duration of a thing. Basically a chronometer with simple chronometer features.",
        keywords: [
          "chronometer",
          "time",
          "lap",
          "duration",
          "measure",
          "pause",
          "resume",
          "stopwatch",
        ],
        category: "Measurement",
      },
      {
        slug: "temperature-converter",
        path: "/temperature-converter",
        name: "Temperature converter",
        description:
          "Degrees temperature conversions for Kelvin, Celsius, Fahrenheit, Rankine, Delisle, Newton, Réaumur, and Rømer.",
        keywords: [
          "temperature",
          "converter",
          "degree",
          "Kelvin",
          "Celsius",
          "Fahrenheit",
          "Rankine",
          "Delisle",
          "Newton",
          "Réaumur",
          "Rømer",
        ],
        category: "Measurement",
      },
      {
        slug: "benchmark-builder",
        path: "/benchmark-builder",
        name: "Benchmark builder",
        description:
          "Easily compare execution time of tasks with this very simple online benchmark builder.",
        keywords: [
          "benchmark",
          "builder",
          "execution",
          "duration",
          "mean",
          "variance",
        ],
        category: "Measurement",
        createdAt: "2023-04-05",
      },
    ],
  },
  {
    name: "Text",
    tools: [
      {
        slug: "lorem-ipsum-generator",
        path: "/lorem-ipsum-generator",
        name: "Lorem ipsum generator",
        description: "Generate random lorem ipsum placeholder text.",
        keywords: [
          "lorem",
          "ipsum",
          "dolor",
          "sit",
          "amet",
          "placeholder",
          "text",
          "filler",
          "random",
          "generator",
        ],
        category: "Text",
      },
      {
        slug: "text-statistics",
        path: "/text-statistics",
        name: "Text statistics",
        description: "Count characters, words, lines and byte size of your text.",
        keywords: [
          "text",
          "statistics",
          "length",
          "characters",
          "count",
          "size",
          "bytes",
        ],
        category: "Text",
        redirectFrom: ["/text-stats"],
      },
      {
        slug: "emoji-picker",
        path: "/emoji-picker",
        name: "Emoji picker",
        description: "Pick and copy emojis by category or search.",
        keywords: ["emoji", "picker", "unicode", "copy", "paste"],
        category: "Text",
        createdAt: "2023-08-07",
      },
      {
        slug: "string-obfuscator",
        path: "/string-obfuscator",
        name: "String obfuscator",
        description: "Hide parts of a string by masking characters.",
        keywords: [
          "string",
          "obfuscator",
          "secret",
          "token",
          "hide",
          "obscure",
          "mask",
          "masking",
        ],
        category: "Text",
        createdAt: "2023-08-16",
      },
      {
        slug: "numeronym-generator",
        path: "/numeronym-generator",
        name: "Numeronym generator",
        description: "Generate numeronyms like i18n, a11y or l10n from words.",
        keywords: [
          "numeronym",
          "generator",
          "abbreviation",
          "i18n",
          "a11y",
          "l10n",
        ],
        category: "Text",
        createdAt: "2023-11-05",
      },
      {
        slug: "ascii-text-drawer",
        path: "/ascii-text-drawer",
        name: "ASCII Art Text Generator",
        description: "Create ASCII art text with many fonts and styles.",
        keywords: ["ascii", "asciiart", "text", "drawer"],
        category: "Text",
        createdAt: "2024-03-03",
      },
      {
        slug: "text-diff",
        path: "/text-diff",
        name: "Text diff",
        description: "Visual diff tool for comparing two pieces of text.",
        keywords: ["text", "diff", "compare", "string", "text diff", "code"],
        category: "Text",
        createdAt: "2023-08-16",
      },
      {
        slug: "keyword-highlighter",
        path: "/keyword-highlighter",
        name: "Keywords highlighter",
        description: "Highlight first and repeated occurrences of keywords in text with custom colors.",
        keywords: ["keyword", "highlight", "text", "first", "occurrence"],
        category: "Text",
      },
      {
        slug: "line-ending-converter",
        path: "/line-ending-converter",
        name: "Line ending converter",
        description: "Convert line endings between CRLF, LF and CR.",
        keywords: ["line", "ending", "crlf", "lf", "cr", "converter", "newline"],
        category: "Text",
      },
    ],
  },
  {
    name: "Lifestyle",
    tools: [
      {
        slug: "schedule-workbench",
        path: "/schedule-workbench",
        name: "日程工作台",
        description:
          "多日程表工作台：新建/导入多个日程表，按名称搜索，每个日程表可展开收起、下载图片、导出、打印。",
        keywords: [
          "schedule",
          "calendar",
          "日程工作台",
          "日程表",
          "课程表",
          "家庭",
          "任务",
        ],
        category: "Lifestyle",
      },
      {
        slug: "daily-grow",
        path: "/daily-grow",
        name: "Daily Grow Tracker",
        description:
          "Track children's daily habits with check-ins, star rewards, weekly/monthly/annual progress boards, class schedules, and multi-child profiles.",
        keywords: [
          "daily",
          "grow",
          "habit",
          "check-in",
          "children",
          "kids",
          "stars",
          "rewards",
          "schedule",
          "growth",
          "打卡",
          "成长",
          "习惯",
          "儿童",
        ],
        category: "Lifestyle",
      },
    ],
  },
  {
    name: "Design",
    tools: [
      {
        slug: "css-style-gallery",
        path: "/css-style-gallery",
        name: "CSS style gallery",
        description:
          "Browse and edit small, reusable CSS/HTML UI snippets such as loading animations, buttons, radios and checkboxes.",
        keywords: [
          "css",
          "gallery",
          "design",
          "loading",
          "button",
          "radio",
          "checkbox",
          "snippet",
          "组件",
          "样式",
        ],
        category: "Design",
      },
    ],
  },
];

export const allTools: ToolConfig[] = toolsByCategory.flatMap(
  (c) => c.tools,
);

export function getToolBySlug(slug: string): ToolConfig | undefined {
  const path = `/${slug}`;
  return allTools.find((t) => t.path === path || t.slug === slug);
}

export function getToolByPath(path: string): ToolConfig | undefined {
  return allTools.find((t) => t.path === path);
}


