/* eslint-disable no-console */
// ReacTools: generate flattened i18n messages from YAML locale files.
// Source: /locales/*.yml
// Output: /lib/i18n/messages.generated.ts

const fs = require("fs");
const path = require("path");
const { parse } = require("yaml");

const rootDir = path.resolve(__dirname, "..");
const localesDir = path.join(rootDir, "locales");
const outputFile = path.join(rootDir, "lib", "i18n", "messages.generated.ts");

/**
 * Recursively flattens a nested object into dot-separated keys.
 * Example: { home: { title: "x" } } -> { "home.title": "x" }
 * Arrays are stringified as-is.
 * @param {any} obj
 * @param {string} prefix
 * @param {Record<string, string>} target
 */
function flattenObject(obj, prefix = "", target = {}) {
  if (obj == null) return target;

  for (const [key, value] of Object.entries(obj)) {
    const nextKey = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      flattenObject(value, nextKey, target);
    } else {
      target[nextKey] = String(value);
    }
  }

  return target;
}

function main() {
  if (!fs.existsSync(localesDir)) {
    throw new Error(`Locales directory not found: ${localesDir}`);
  }

  const files = fs
    .readdirSync(localesDir)
    .filter((f) => f.endsWith(".yml") || f.endsWith(".yaml"))
    .sort();

  if (files.length === 0) {
    throw new Error(`No *.yml files found in ${localesDir}`);
  }

  /** @type {Record<string, Record<string, string>>} */
  const messages = {};

  for (const file of files) {
    const locale = path.basename(file, path.extname(file));
    const fullPath = path.join(localesDir, file);
    const source = fs.readFileSync(fullPath, "utf8");
    const data = parse(source) || {};
    messages[locale] = flattenObject(data);
  }

  const locales = Object.keys(messages);

  const header = [
    "/* eslint-disable */",
    "// This file is auto-generated by scripts/generate-i18n.cjs.",
    "// Do not edit this file directly; edit YAML files in /locales and re-run the generator.",
    "",
  ].join("\n");

  const body =
    "export const generatedMessages = " +
    JSON.stringify(messages, null, 2) +
    " as const;\n" +
    "export type GeneratedMessages = typeof generatedMessages;\n" +
    "export type GeneratedLocale = keyof GeneratedMessages;\n";

  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(outputFile, `${header}${body}`, "utf8");

  console.log(
    `Generated ${path.relative(rootDir, outputFile)} for locales: ${locales.join(
      ", ",
    )}`,
  );
}

main();

